### ISSUE TITLE
Got Error Close the tag with Raimondi/delimitMate.vim

### ISSUE THREAD

**Issue by DemonCloud** [alvan/vim-closetag#1]
[delimitMate](https://github.com/Raimondi/delimitMate)

delimitMate auto close the `>` encode

`<|`  -> `<|>`

`<div>>|` -> `<div></div>>`

**Comment by DemonCloud** [comment]
I finally fix it with fill them to my vimrc

``` VimL
let g:closetag_filenames = "*.xml,*.html,*.xhtml,*.phtml,*.php"
au FileType xml,html,phtml,php,xhtml,js let b:delimitMate_matchpairs = "(:),[:],{:}"
```

**Comment by alvan** [comment]
Thank you for pointing out this issue,
I think some other users that using this plugin will get help from your solution.
