### ISSUE TITLE
Temporarily disable at runtime

### ISSUE THREAD

**Issue by symbyte** [alvan/vim-closetag#10]
Is there a way to temporarily disable this plugin at runtime through an ex command? I am using this in Typescript to edit template strings that contain html but it has the side effect of interpreting generic types like `List<MyType>` as tags and auto closes them as well.

**Comment by gurdiga** [comment]
I’m wondering if it’d make it easier to implement this as a special case. When saying “special case” I’m thinking about the other special case described [in the README](https://github.com/alvan/vim-closetag/blob/master/README.md): `>`. If you type this:
```
<a>>
```
you get not only the closing tag, but it also breaks the tag and inserts a couple of newlines and in the end you get this:
```
<a>
    |       <––––– cursor ends up here
</a>
```
So this other special case could be something like:
```
List<MyType>«hit Backspace key here»
```
and this would result in the removal of the auto-closed tag, and end up with this:
```
List<MyType>
```
🤓 

@symbyte I’m wondering if you thought about a particular implementation? 🤔

**Comment by gurdiga** [comment]
Just in case: the way I work around unwanted closing tags is that I first type both angle brackets: `<>`, and then move cursor one left and type in whatever I need. It’s a bit of change in the workflow, but works. 🤓

**Comment by woat** [comment]
@gurdiga I think I might have found a *slightly* efficient way than that, though just as hacky.

If you wouldn't mind adding a line to your .vimrc you could implement:
```imap <leader>z <ESC>ldf>a```

Of course  you can change the mapping toward your preference, but in my case, I have `,z` which will delete the matching tag. Typing that is much faster than going from insert to normal mode, insert back a space, typing inside the brackets, esc, insert after (`<><ESC>i{{tag element + attributes}}<ESC>a`).

**Comment by alvan** [comment]
Hi guys,
I have add two ex commands to enable/disable this function for current buffer:
```
:CloseTagEnableBuffer
:CloseTagDisableBuffer
```

You can try by yourselves.
