### ISSUE TITLE
Auto close in JSX

### ISSUE THREAD

**Issue by oscarmorrison** [alvan/vim-closetag#11]
I have added this to my VIMRC:
`let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.php, *.jsx"`

but auto closing tags does not work.

**Comment by oscarmorrison** [comment]
Stupid me. 
I had an additional space before *.jsx

This is working:
`let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.php,*.jsx"`

**Comment by teclagual** [comment]
@oscarmorrison I had the exact same problem and was about to give up.

**Comment by przbadu** [comment]
I have this configuration:

```
let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.erb,*.jsx"
let g:closetag_xhtml_filenames = '*.xhtml,*.jsx,*.erb'
let g:closetag_emptyTags_caseSensitive = 1
let g:closetag_shortcut = '>'
let g:closetag_close_shortcut = '<leader>>'
```
And still it doesn't work for my jsx configuration. It works for all other extensions though. Any help would be appreciated.

![vim-closetag-issue](https://user-images.githubusercontent.com/4189129/28955832-e84d1e46-7908-11e7-827d-186b54f37b5d.gif)

**Comment by alvan** [comment]
@przbadu 
I just copy your configuration for testing, it works.
Please disable other plugins and try again.

**Comment by alvan** [comment]
@przbadu 
Related issue https://github.com/alvan/vim-closetag/issues/24

**Comment by Bhanukamax** [comment]
adding the following worked for me:
`let g:closetag_xhtml_filetypes = 'xhtml,javascript.jsx,jsx'`

also I have this to set the file type: 
`autocmd BufNewFile,BufRead *.js set filetype=javascript.jsx`
`autocmd BufNewFile,BufRead *.jsx set filetype=javascript.jsx`
