### ISSUE TITLE
Weird behavior pasting HTML

### ISSUE THREAD

**Issue by oscarmorrison** [alvan/vim-closetag#12]
I am having some troubles pasting some HTML into a .jsx file with autopairs turned on

`<blockquote>This is a blockquote</blockquote><p><br></p><h1>This is a header</h1>`

ends up as 

`<blockquote>This is a blockquote</blockquote><p><br></p><h1>This is a header</h1></h1></p></blockquote>`

**Comment by alvan** [comment]
@oscarmorrison 
I suggest you can disable some other plugins and try it again.
Here I can't reproduce this issue.
