### ISSUE TITLE
vim-closetag broken in html like files with extensions other than .html

### ISSUE THREAD

**Issue by joerideg** [alvan/vim-closetag#13]
Hi!

First of all thanks for the great work.

At this point when I update closetag to the latest version it doesnt work even if its the only plugin loaded. When I go back to commit 00e1155cee8bf9859fd378558a1a5c950a3d5be3 it does work. So it seems that when you removed 'unnecessary code' you removed a bit too much :)

**Comment by nhooyr** [comment]
It seems to be working fine for me. What's wrong with it?

**Comment by joerideg** [comment]
After your comment I tried stuff out a bit more detailed.
So the problem doesnt seem to occur in files with extension .html with any filetype (be it html or html.handlebars or html.ejs) but it will occur in files with extenions like .hbs or .ejs even when their filetype is set to html.

I guess the solution would be to make this plugin effective based on filetype and not extension?

I thought commit `00e1155` was the difference, but I guess I was testing out html files and ejs/hbs files and drew the wrong conclusion.

**Comment by joerideg** [comment]
Ah and now I see that there is a specific option for it in the readme. My bad! Closing the issue
