### ISSUE TITLE
Vim/Neovim frozen after editing a tag in the first level

### ISSUE THREAD

**Issue by gerardbm** [alvan/vim-closetag#14]
Hi! First of all, thanks for your good plugin. It is really useful.

Under a certain conditions, Vim or Neovim stay frozen after editing a tag. I tried it in HTML and XML. The way to reproduce it:

1. Must be the first tag level. So a new file editing the first line will be enough for the test. Let's call it `xml.xml`.
2. Insert a tag called `<test>` and the plugin will insert `</test>` perfectly.
3. Now press `>` again to create the indent for the following tag:
```
<test>
    |
</test>
```
4. Still into 'Insert mode', let's remove the indentation. I press 2 times `<BS>` and 1 time `<Del>`. **What happens if you press 2 times `<Del>` by mistake?** You will have this:
```<test>|/test>```
5. Ok, it was a mistake. Let's enter again the missing `<`... But nothing is happening. Literally nothing. You can't `<Esc>`, you can't close Vim. I had to close the tmux pane/window.

Can you reproduce it? Thanks in advance!

**Update**: I upload an animated GIF. As you can see, I can't close the 'Insert mode' pressing `<Esc>`. Actually, I had to kill the process with `sudo kill -2 {PID}` because Vim was consuming 100% of the CPU (even after closing Vim deleting the tmux pane).

![closetag](https://cloud.githubusercontent.com/assets/5253997/21034067/43d7a58e-bdb5-11e6-9d0a-89f761817a0e.gif)

**Comment by alvan** [comment]
Hi, @gerardbm.
Sorry, I tried it, but I can not reproduce it, both in macvim or terminal.
Actually this plugin only bind the key ">", so when you press "<", it should not cause any problem.
I think you can try to update your vim if possible.

Below is my vim version info:
`:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 16 2016 15:06:37)
MacOS X (unix) version
Included patches: 1-41
Compiled by Homebrew
`

**Comment by gerardbm** [comment]
Hi, @alvan.

I discovered a new condition to reproduce it. The issue happens only if you have a `iab` in the configuration. For example, `iab teh the`. Could you try it to confirm it?

Tested in:
- Vim 7.4 patches 1-882
- Vim 8.0 patches 1-124
- Nvim 2.0-dev

Both Vim tests were with the minimal configuration and removing all the plugins excepting this one, installed through vim-plug.

**Comment by gerardbm** [comment]
Hi, again.

It works fine now on:
- Vim 8.0 patches 1-313, 315-604 on Ubuntu 14.04 and Arch Linux
- Nvim 1.7 on Arch Linux
- Nvim 2.0 on Arch Linux

It's not working on:
- Nvim 2.0-dev on Ubuntu 14.04
- Nvim 2.1-dev on Ubuntu 14.04

I think it's more related on the old Nvim dependencies from Ubuntu 14.04, so I close this issue.
