### ISSUE TITLE
Ends the completing tag with an extra ">"

### ISSUE THREAD

**Issue by dreadnoughtsix** [alvan/vim-closetag#16]
As I follow through with what the instructions tell me to do, the autocompleting tag, for example, `<div>` will complete with `</div>>`

**Comment by dreadnoughtsix** [comment]
It may have something to do with my bracket autocompleting plugin too

**Comment by dreadnoughtsix** [comment]
Here is the bracket autocomplete plugin: 

https://github.com/vim-scripts/delimitMate.vim

**Comment by alvan** [comment]
@dreadnoughtsix 
I checked the docs of delimitMate.vim,
If you want to use these two plugins together, you may need to disable the auto-pair feature for "<>" provided by delimitMate.vim.

Try to remove "<:>" from this delimitMate option:

`Let delimitMate_matchpairs =" (:), [:], {:}, <:> "`

Set:

`Let delimitMate_matchpairs =" (:), [:], {:} "`

**Comment by b0rn-c0mpl3x3d** [comment]
Awesome ^_^ just write let in small letter and remove the spaces between the braces :

> let delimitMate_matchpairs ="(:),[:],{:}"
