### ISSUE TITLE
wrong close in quotation

### ISSUE THREAD

**Issue by jtr109** [alvan/vim-closetag#19]
Hi, your plugin is awesome! I have use it for a long time.

But I met an issue that it not works well in attribute value. If I want to insert a attribute in class. For example:

```html
<div class="a|"></div>
<!-- "|" is the cursor placed -->
```

If I hit the <kbd>></kbd>, the `vim-closetag` will make effect and the line will be like this:

```html
<div class="a></div>"></div>
```

It is not what it should be. And it makes trouble when using `ng-if` or `v-if` in angularjs or vuejs.

**Comment by davidsierradz** [comment]
Also in Laravel Blade for example:

`<form method="POST" action="reply/{{ $reply-| }}"></form>`

after hit `>`:

`<form method="POST" action="reply/{{ $reply->|</form> }}"></form>`

Maybe a setting to exclude the plugin to autocomplete on certain regions? like `" "` or `{{ }}`

Thanks!

**Comment by alvan** [comment]
Guys, please try the new version.
I have made some changes.

**Comment by jtr109** [comment]
Great! It works well! Thanks a lot! 🍾
