### ISSUE TITLE
Too much indentation when `set noexpandtab virtualedit=all`

### ISSUE THREAD

**Issue by olmokramer** [alvan/vim-closetag#20]
When I `set noexpandtab virtualedit=all` I get wrong indentation on the empty line inserted between two tags. For example when I start out like
```html
<html>|</html>
```
and press <kbd>&gt;</kbd> I get this (a tab and 7 spaces):
```html
<html>
→       ⋅⋅⋅⋅⋅⋅⋅|
</html>
```
Setting either `set expandtab` or `set virtualedit=` fixes the problem. I can't live without either of these options, so it would be really nice if this can be fixed another way.

I have also `set` these options, they may be relevant, but don't seem to change the behavior when I change/disable them.
```vim
set autoindent
set shiftwidth=8
set smartindent
set smarttab
set softtabstop=8
set tabstop=8
```

**Comment by olmokramer** [comment]
<strike>Ok this is really weird. `set virtualedit=block,insert,onemore` inestead of `set virtualedit=all` solves the problem, even though they ought to do the same thing...</strike>
Never mind, `set virtualedit=block,insert,onemore` is not the same as `set virtualedit=all`

**Comment by alvan** [comment]
@olmokramer  Fixed, please try again.

**Comment by olmokramer** [comment]
Yes it seems to work. Thanks!
