### ISSUE TITLE
Give option to choose which filetypes should be treated as XHTML

### ISSUE THREAD

**Issue by maxmellen** [alvan/vim-closetag#21]
Today, in order to properly handle _empty_ tags in JSX which closes empty elements like XHTML, I have two `autocmd`s change the global variable `g:closetag_use_xhtml` depending on the file extension.
This option is not documented in the README, so I'm not sure if I should actually use it.

I currently have the following in my `.vimrc`
```vim
let g:closetag_filenames = '*.html,*.js'
let g:closetag_emptyTags_caseSensitive = 1
autocmd BufNewFile,Bufread *.html let g:closetag_use_xhtml = 0
autocmd BufNewFile,Bufread *.js let g:closetag_use_xhtml = 1
```

But I think it would be nicer to have something like:
```vim
let g:closetag_filenames = '*.html'
let g:closetag_xhtml_filenames = '*.js'
let g:closetag_emptyTags_caseSensitive = 1
```

What do you think?

**Comment by alvan** [comment]
@maxmellen 
For this case, I would suggest you change the local buffer variable `let b:closetag_use_xhtml = 1` for xhtml files.

**Comment by alvan** [comment]
Added new global option g:closetag_xhtml_filenames

**Comment by maxmellen** [comment]
@alvan, Awesome! Thanks for the addition!

**Comment by nixpulvis** [comment]
Ok I'm struggling to figure out what this option actually does without digging though the code. It doesn't seem to change the behavior of anything to me.
