### ISSUE TITLE
Autoclose issue in JSX

### ISSUE THREAD

**Issue by przbadu** [alvan/vim-closetag#24]
I have this configuration:

```
let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.erb,*.jsx"
let g:closetag_xhtml_filenames = '*.xhtml,*.jsx,*.erb'
let g:closetag_emptyTags_caseSensitive = 1
let g:closetag_shortcut = '>'
let g:closetag_close_shortcut = '<leader>>'
```
And still it doesn't work for my jsx configuration. It works for all other extensions though. Any help would be appreciated.

![vim-closetag-issue](https://user-images.githubusercontent.com/4189129/28955832-e84d1e46-7908-11e7-827d-186b54f37b5d.gif)

**Comment by alvan** [comment]
@przbadu 
I just copied your configuration for testing, it works.
Please disable other plugins and try again.

**Comment by przbadu** [comment]
@alvan thanks, but I tried to disable lots of configuration files and almost all plugins. but still was unable to figure it out. I am trying to update this plugin and then will try again to debug.

**Comment by alvan** [comment]
@przbadu 
Yes, and please also try to update your Vim to the latest version.
Below is my vim version info:
`
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 24 2017 12:45:56)
`

Hope this will help you.

**Comment by przbadu** [comment]
@alvan: Yes already using `vim 8.0.636`, FYI

**Comment by przbadu** [comment]
😅 😅  I am so stupid, I have used `vim-scripts/HTML-AutoCloseTag` plugin and wasting my time debugging what's wrong. Now using correct plugin and it is working. Sorry guys.
