### ISSUE TITLE
Not Working with .html files

### ISSUE THREAD

**Issue by deepanshurana** [alvan/vim-closetag#26]
The plugin isn't working , my **.vimrc** file has : 
`let g:closetag_filenames = '*.html,*.xhtml,*.phtml'`
and I downloaded the plugin with pathogen by following commands:
` cd ~/.vim/bundle `
`git clone https://github.com/alvan/vim-closetag.git`

**Comment by alvan** [comment]
@deepanshurana 
Please make sure you have installed this plugin first:
`:echo g:loaded_closetag`
&
`:echo g:closetag_shortcut`
