### ISSUE TITLE
Delay after pressing <Leader>

### ISSUE THREAD

**Issue by chaucerbao** [alvan/vim-closetag#27]
There's a noticeable delay after pressing `<Leader>` in insert mode since 527bb10664b999dee6b5cfb3adce666f7d4cf0f8.

**Comment by alvan** [comment]
@chaucerbao 
It's because there have a new shortcut: '<leader>>'.
If you don't need this, please add following line to your vimrc:
`let g:closetag_close_shortcut = ''`

Or you can change it to another key.

**Comment by chaucerbao** [comment]
Got it, thanks!  Didn't realize that was a new feature.

**Comment by duleorlovic** [comment]
Can default be something another than <leader> key ?
I'm sure that this issue notice a lot of people.

**Comment by alvan** [comment]
@duleorlovic
Guys,
I decided to set the default value of `g:closetag_close_shortcut` to an empty string
