### ISSUE TITLE
Extra closing tag in html file

### ISSUE THREAD

**Issue by n3vwabgb** [alvan/vim-closetag#28]
I'm pretty sure this problem is on my end only but I can't seem to find a fix. When using close tag I get an extra closing tag in html files as displayed by the picture underneath. Any help would be greatly appreciated, thank you in advance.

![screenshot from 2017-06-24 08-16-99](https://user-images.githubusercontent.com/13586451/31924395-b7902f52-b835-11e7-839c-b5e86ee1f2b6.png)

**Comment by alvan** [comment]
@n3vwabgb 
I guess you are using another plugin that helps you close the "<" automatically.
You can refer to this closed issue for more details: https://github.com/alvan/vim-closetag/issues/16

**Comment by n3vwabgb** [comment]
Sorry didn't see that, that did the job. Thank you so much.
