### ISSUE TITLE
Ill behaved >> for multiline tag

### ISSUE THREAD

**Issue by namedots** [alvan/vim-closetag#29]
Tested with only the plugin in .vim and an empty .vimrc :

```
$ cd ~
$ mv .vim vimbackup
$ mv .vimrc vimbackuprc
$ touch .vimrc
$ git clone git@github.com:alvan/vim-closetag.git .vim
$ cd .vim
$ git rev-parse HEAD  # current commit
8496544ba82a210b66ab2d8283609f65a36d92a6
$ vim --version | head -n2
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  7 2017 13:50:55)
Included patches: 1-1176
$ vim hello.html
```

`|` as cursor position
```
<form method="POST"
      action="stuff"|
```
enter `>>`
```
<form method="POST|
      action="stuff">></form>
```
(note dissappeared `"`, cursor having moved UP, one too many `>`, no new lines for cursor and closing tag)

expected outcome:
```
<form method="POST"
      action="stuff">
|
</form>
```
(or similar, with valid form tag and cursor and closing tag on their own lines)

**Comment by alvan** [comment]
@CookiesBestDinner 
Thank you for your detailed description.
This issue has been fixed, you can try it again.

**Comment by namedots** [comment]
Wonderful! Thank you.
