### ISSUE TITLE
Toggle Buffer?

### ISSUE THREAD

**Issue by iFallUpHill** [alvan/vim-closetag#30]
CloseTagEnableBuffer and CloseTagDisableBuffer are great, but it would be even better if there were a way to toggle the plugin to make keybinds a little bit cleaner.

**Comment by alvan** [comment]
@iFallUpHill 
I just added a new command :CloseTagToggleBuffer.
You can try it.

**Comment by iFallUpHill** [comment]
Works perfectly, thanks!
