### ISSUE TITLE
Feature Request: Disable auto-close when pasting

### ISSUE THREAD

**Issue by jktzes** [alvan/vim-closetag#32]
When I copy and past code, it will add extra tags at the bottom.
<img width="1112" alt="screen shot 2018-03-23 at 2 26 56 pm 2" src="https://user-images.githubusercontent.com/17117898/37849600-4ead3ca4-2ea6-11e8-93e5-6c40f3f90793.png">

**Comment by alvan** [comment]
@jktzes 
Sorry but I can't reproduce this issue.
Can you provide more details such as your Vim configuration, how do you operate it, and what shortcuts do you use?
In addition, I guess this is caused by the automatic indentation plugin you use.
You can try and check it again.
