### ISSUE TITLE
Add option to add closing tag on separate line?

### ISSUE THREAD

**Issue by mqudsi** [alvan/vim-closetag#38]
Would it be possible to add an option to configure the default closing tag location? Currently, it is unconditionally added immediately after the closing `>`, but it can be desirable to have it added on the next line for people that prefer opening and closing tags on their own lines.

**Comment by alvan** [comment]
@mqudsi 
The current approach is to press the ">" twice and then the close tag will be placed on the next line.

**Comment by mqudsi** [comment]
Awesome, I completely glossed over that section of the docs.
