### ISSUE TITLE
Closes tag when `>` is seen inside of an attribute value

### ISSUE THREAD

**Issue by dnd** [alvan/vim-closetag#39]
I'm currently building an app with Vue, where the templating will at times have `>` comparisons inside of an attribute value. When that character is entered, closetag immediately closes the tag, even though it shouldn't.

Typing `<div :complete="1 >` will immediately result in `<div :complete="1></div>`. When using the auto-pairs plugin to insert a closing quote as soon as the opening is typed closetag ends up with `<div :complete="1 >"` being converted to `<div :complete="1 ></div>"`.

Is there any kind of setting/flag I need to set, or is this a bug?

**Comment by alvan** [comment]
@dnd 
I can't reproduce this issue.
Please check if you are using other plugins for auto closing tags.

**Comment by redbmk** [comment]
This happens in `jsx`:

For example trying to write this: `<Checkbox checked={numItems > 0}>Has Items</Checkbox>`

You will get `<Checkbox checked={numItems > </Checkbox>`

**Comment by alvan** [comment]
This plugin is mainly used in HTML tags. I don't intend to add support for other syntaxes, because that is basically impossible. Automatically completing tags for specific syntax is a complicated task for such a plugin.

**Comment by alvan** [comment]
Please use `<leader>>` to insert ">" directly in this case.
