### ISSUE TITLE
feature request: do not close tag if the end tag already exists

### ISSUE THREAD

**Issue by redbmk** [alvan/vim-closetag#41]
For example, say you already have this in your code:

```
<div className="test">
  Hello world
</div>
```

Then you want to change it to:
```
<div>
  Hello world
</div>
```

One way you might do this is to move the cursor to the end of the first `div`, then type `C` to go to the end of the line, then type `>` to close the first `div` tag:

```
<div|
  Hello world
</div>
```

As soon as you press `>` you get:
```
<div></div>
  Hello world
</div>
```

There are plugins that can detect and highlight the closing tag (e.g. https://github.com/Valloric/MatchTagAlways), so it seems like this should be possible (check if there's a match already once `>` is entered, and only add the closing tag if it's not already there).

The workaround of course would be not to delete the `>`, by doing `dt>` or `ct>` instead of `C`, but I think this would be a nice feature.

**Comment by alvan** [comment]
Please use `<leader>>` to insert ">" directly in this case.
