### ISSUE TITLE
TSX?

### ISSUE THREAD

**Issue by joselevelsup** [alvan/vim-closetag#44]
Love this plugin by the way. I tried to include `.tsx` file types in to the variable in my `init.vim` file. it looks like:

`let g:closetag_filenames = '*.html,*.jsx,*.tsx'`

It doesn't auto close for TSX files but JSX works just fine. Any thoughts or something I may be doing wrong?

**Comment by madox2** [comment]
In my case the tags are also not auto-closing in combination with [ianks/vim-tsx](https://github.com/ianks/vim-tsx) plugin. I suppose there must be conflict between plugins.

When I uninstall ianks/vim-tsx, auto-closing works but also outside of jsx (what is quite inconvenient especially when writing some generics stuff).

**Comment by jarneson** [comment]
There's a `g:closetag_regions` variable you can set to define which syntax regions you want to have completion in. My config:
```
let g:closetag_regions =  {
\ 'typescript.tsx': 'jsxRegion,tsxRegion',
\ 'javascript.jsx': 'jsxRegion',
\ }
```

**Comment by vegawong** [comment]
@jarneson it works! nice:)

**Comment by joselevelsup** [comment]
Sorry for the late reply but @jarneson that definitely helped. Thanks!
