### ISSUE TITLE
Autoclose not working in only JSX, TSX

### ISSUE THREAD

**Issue by mununki** [alvan/vim-closetag#45]
Hi, I love your wonderful work.

Actually, It works like charms with `*.html`. I tried many times and many ways with `*.jsx` and `*.tsx`, but failed.
Below is my configuration. Any clue?

```
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'rust-lang/rust.vim'
Plugin 'ervandew/supertab'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'maxmellon/vim-jsx-pretty'
Plugin 'leafgarland/typescript-vim'
Plugin 'w0rp/ale'
Plugin 'alvan/vim-closetag'

call vundle#end()
```
```
let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.erb,*.jsx,*.tsx"
let g:closetag_xhtml_filenames = '*.xhtml,*.jsx,*.tsx,*.erb'
let g:closetag_emptyTags_caseSensitive = 1
let g:closetag_shortcut = '>'
let g:closetag_close_shortcut = '<leader>>'
```

**Comment by alvan** [comment]
Hi @mattdamon108 

Basically you only need to set:
`let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.erb,*.jsx,*.tsx"`

And please try to disable some of the related plugins to determine if there is a conflict.

**Comment by mununki** [comment]
@alvan Thanks! It works like charm!
Sorry for my lack of understanding the documentation enough.
