### ISSUE TITLE
It does not work with .html.erb files

### ISSUE THREAD

**Issue by itsdaiego** [alvan/vim-closetag#5]
I'm trying to use this Plugin with .html.erb files (ruby on rails) but it does not work.

it works with anything ending with a ".html" 

but it won't work if the file has ".erb" (or haml for example)

Thanks.

**Comment by alvan** [comment]
Try this:
`let g:closetag_filenames = "*.html.erb,*.html,*.xhtml,*.phtml"`

**Comment by itsdaiego** [comment]
Thanks a lot @alvan  it works!!

**Comment by kikikiblue** [comment]
html tags are work well in erb files. 
Can I use this plugin for autoclose erb template tag?
for example, 

if I enter `<%|`  I want to get `<%|%>`
