### ISSUE TITLE
Config with file .js

### ISSUE THREAD

**Issue by khaitranhq** [alvan/vim-closetag#53]
Hi,
My project use react written in .js file
I try to config to apply config of vim-closetag to js file but it's not working
Thanks for any helps

**Comment by henryoliver** [comment]
@lioaslan just add this to your `.vimrc` config file:
```
" Vim Closetag
let g:closetag_filetypes = 'html,xhtml,jsx,javascript'

```

**Comment by goldylucks** [comment]
Also doesn't work for me with this config:

```
let g:closetag_filetypes = 'html,xhtml,jsx,javascript'
let g:closetag_xhtml_filetypes = 'xhtml,javascript'
```

@henryoliver any other ideas?

**Comment by JakeElder** [comment]
@goldylucks - If you type `:set filetype?` in the file you would like to auto close tags in, vim will output the `filetype` of the current buffer.

![2020-06-09 06 31 36](https://user-images.githubusercontent.com/1167624/84090175-27652380-aa1b-11ea-8e9b-21dee87ee3ef.gif)

You could try adding that to your `g:closetag_filetypes` variable declaration in your .vimrc.

From my vimrc
```vim
" Enable auto close tags with <tag|>
" Skip with <leader>>
let g:closetag_filetypes = 'html,typescript.tsx'
let g:closetag_close_shortcut = '<leader>>'

```

This works for me as I default all js,jsx,ts,tsx to `typescript.tsx`

```vim
" Set filetype=typescript.tsx (required by coc-tsserver)
" Set syntax as typescriptreact (for default vim ts syntax)
" Set the same for js, jsx, ts, tsx so highlighting is consistent
autocmd BufNewFile,BufRead *.js,*.ts
      \ set filetype=typescript.tsx |
      \ set syntax=typescriptreact
```

**Comment by goldylucks** [comment]
I don't know what happened but now it seems to be working :)

**Comment by dangtony98** [comment]
> @lioaslan just add this to your `.vimrc` config file:
> 
> ```
> " Vim Closetag
> let g:closetag_filetypes = 'html,xhtml,jsx,javascript'
> ```

This worked perfectly! Thank you.
