### ISSUE TITLE
Better autocomplete of self-closing tags

### ISSUE THREAD

**Issue by AlexAegis** [alvan/vim-closetag#54]
Right now self-closing tags are not expanded, which is good enough, but the proper way of closing them is `/>`.

Either, when typing `>` on such tag expand it to `/>`, or let `/` expand into `/>`, or both. (If `/` would extend to '/>', if the very next input is `>`, ignore it and move the cursor to the right. Or forget if the mode has been switched.)

The second option looks a bit more complicated than just letting `>` expand "backwards" into `/>`

> It's true that the ending slash in HTML5 is optional but in XHTML it's required.

**Comment by alvan** [comment]
This is an already supported feature. But this feature is only for xhtml files. Please check these two configuration items:
`g:closetag_xhtml_filenames ` and `g:closetag_xhtml_filetypes`
