### ISSUE TITLE
doesn't work for html.erb

### ISSUE THREAD

**Issue by sfahlberg** [alvan/vim-closetag#7]
in my .vimrc, I have `let g:closetag_filenames = "*.html,*.erb"` and yet it doesn't seem to work in .erb files. Any idea why?

**Comment by alvan** [comment]
@sfahlberg 
I tested by using this config: `let g:closetag_filenames = "*.html,*.erb"`, and it works fine when editing *.erb files.
Can you show me the file? 

Or you can refer to this issue: https://github.com/alvan/vim-closetag/issues/5

**Comment by sfahlberg** [comment]
Got it working! Turns out I needed to close and restart my vim instead of just running `:so ~/.vimrc`. Thanks for your quick response! And for a great plugin!
