### ISSUE TITLE
Doesn't work in *.php files

### ISSUE THREAD

**Issue by maxcutlyp** [alvan/vim-closetag#72]
It works fine in *.html and *.phtml files.

Version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 15 2021 21:48:21)

Relevant part of vimrc:
```vim
let g:closetag_filenames = "*.html,*.phtml,*.php"
let g:closetag_xhtml_filenames = "*.xhtml,*.jsx,*.tsx"
let g:closetag_filetypes = "html,phtml,php"
let g:closetag_xhtml_filetypes = "xhtml,jsx,tsx"
let g:closetag_emptyTags_caseSensitive = 1
let g:closetag_regions = {
    \ "typescript.tsx": "jsxRegion,tsxRegion",
    \ "javascript.jsx": "jsxRegion",
    \ "typescriptreact": "jsxRegion,tsxRegion",
    \ "javascriptreact": "jsxRegion",
    \ }
let g:closetag_shortcut = ">"
let g:closetag_close_shortcut = "<leader>>"
```

Gif of the issue
![vim-closetag-php](https://user-images.githubusercontent.com/46881987/141739735-a3a43d24-2130-46cc-a68d-f25ad861f0d9.gif)

**Comment by alvan** [comment]
This should not be an issue with the plugin, please check your filetype related configuration.
