### ISSUE TITLE
Closing "p" tag with second ">" doesn't indent new line

### ISSUE THREAD

**Issue by jeremy-beasley** [alvan/vim-closetag#74]
Pressing ">" twice to close a `p` tag (once, to close; again to create a new line) doesn't result in an indented newline. This was strange because it works for all of the other tags, e.g. `<section>`, `<div>`, `<nav>`. 

Am I missing something?

**Comment by alvan** [comment]
Please check your indentation settings. Many html plugins don't indent content inside `p` tags.
