### ISSUE TITLE
Doesn't work using dein lazy load

### ISSUE THREAD

**Issue by andersonba** [alvan/vim-closetag#9]
Doesn't work

``` vim
call dein#add('alvan/vim-closetag', {'lazy':1, 'on_ft': ['html', 'htmldjango', 'xhtml', 'jinja']})
```

Works

``` vim
call dein#add('alvan/vim-closetag', {'lazy':0, 'on_ft': ['html', 'htmldjango', 'xhtml', 'jinja']})
```

**Comment by austincrft** [comment]
It also doesn't work with [vim-plug](https://github.com/junegunn/vim-plug)'s filetype-loading:

``` vim
Plug 'alvan/vim-closetag', { 'for': ['html', 'xml'] }
```

**Comment by CallumHoward** [comment]
+1

**Comment by alvan** [comment]
I pushed a new commit to support vim-plug's filetype-loading, now it should work.
But actually, I don't think lazy-loading is necessary for this plugin since this plugin itself can handle specified file types(names).
So I will close this issue now.
